### ISSUE TITLE
insufficient funds for transfer

### ISSUE THREAD

**Issue by mcfang** [R4vage/open-gsn-react-demo#1]
hi, i run this project. After mint tokens. Transfer tokens return an error:
{"code":-32000,"message":"insufficient funds for transfer"}

**Comment by JulianOfThePipol** [comment]
Fixed transfer. Added buttons to see the user's balance and the transferred account's balance.
Have in mind that this is a very basic implementation. Gas price shouldn't be hardcoded. This project was meant as a very basic example of using meta transactions and opengsn to take care of the user's gas fees.
